---
title: "Codebook"
---

##Intro
The information in this codebook explicitly references the variables in the cleanData.csv found within this repo.

###ID variables
* Subject
* Activity

Activity labels (created using the Activity_labels.txt file from the initial file pack)

* LAYING 
* SITTING 
* STANDING 
* WALKING 
* WALKING_DOWNSTAIRS 
* WALKING_UPSTAIRS

###Measurements
Each meaurements for the following variables are the mean of the raw dataset

* tBodyAcc-mean()-X   
* tBodyAcc-mean()-Y 
* tBodyAcc-std()-Y 
* tGravityAcc-mean()-Y 
* tGravityAcc-std()-Y 
* tBodyAccJerk-mean()-Y 
* tBodyAccJerk-std()-Y 
* tBodyGyro-mean()-Y 
* tBodyGyro-std()-Y 
* tBodyGyroJerk-mean()-Y 
* tBodyGyroJerk-std()-Y 
* tBodyAccMag-std() 
* tBodyAccJerkMag-mean() 
* tBodyGyroMag-std() 
* fBodyAcc-mean()-X 
* fBodyAcc-std()-X 
* fBodyAcc-meanFreq()-X 
* fBodyAccJerk-mean()-X 
* fBodyAccJerk-std()-X 
* fBodyAccJerk-meanFreq()-X 
* fBodyGyro-mean()-X 
* fBodyGyro-std()-X 
* fBodyGyro-meanFreq()-X 
* fBodyAccMag-mean() 
* fBodyBodyAccJerkMag-mean() 
* fBodyBodyGyroMag-mean() 
* fBodyBodyGyroJerkMag-mean() 
* tBodyAcc-mean()-Z 
* tBodyAcc-std()-Z 
* tGravityAcc-mean()-Z 
* tGravityAcc-std()-Z 
* tBodyAccJerk-mean()-Z 
* tBodyAccJerk-std()-Z 
* tBodyGyro-mean()-Z 
* tBodyGyro-std()-Z 
* tBodyGyroJerk-mean()-Z 
* tBodyGyroJerk-std()-Z 
* tGravityAccMag-mean() 
* tBodyAccJerkMag-std() 
* tBodyGyroJerkMag-mean() 
* fBodyAcc-mean()-Y 
* fBodyAcc-std()-Y 
* fBodyAcc-meanFreq()-Y 
* fBodyAccJerk-mean()-Y 
* fBodyAccJerk-std()-Y 
* fBodyAccJerk-meanFreq()-Y 
* fBodyGyro-mean()-Y 
* fBodyGyro-std()-Y 
* fBodyGyro-meanFreq()-Y 
* fBodyAccMag-std() 
* fBodyBodyAccJerkMag-std() 
* fBodyBodyGyroMag-std() 
* fBodyBodyGyroJerkMag-std() 
* tBodyAcc-std()-X 
* tGravityAcc-mean()-X 
* tGravityAcc-std()-X 
* tBodyAccJerk-mean()-X 
* tBodyAccJerk-std()-X 
* tBodyGyro-mean()-X 
* tBodyGyro-std()-X 
* tBodyGyroJerk-mean()-X 
* tBodyGyroJerk-std()-X 
* tBodyAccMag-mean() 
* tGravityAccMag-std() 
* tBodyGyroMag-mean() 
* tBodyGyroJerkMag-std() 
* fBodyAcc-mean()-Z 
* fBodyAcc-std()-Z 
* fBodyAcc-meanFreq()-Z 
* fBodyAccJerk-mean()-Z 
* fBodyAccJerk-std()-Z 
* fBodyAccJerk-meanFreq()-Z 
* fBodyGyro-mean()-Z 
* fBodyGyro-std()-Z 
* fBodyGyro-meanFreq()-Z 
* fBodyAccMag-meanFreq() 
* fBodyBodyAccJerkMag-meanFreq() 
* fBodyBodyGyroMag-meanFreq() 
* fBodyBodyGyroJerkMag-meanFreq()